config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root :to => "home#index"

  resources :todos

end

app/models/todos.rb
class Todos < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		if user_signed_in?
			redirect_to :controller => 'todos', :actioon => 'index'
		end

	end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

	def index
		@todos = Todos.where(done: false)
		@todone = Todos.where(done: true)
	end

	def new
		@todo = Todos.new
	end

	

	def todo_params
		params.require(:todos).permit(:name, :done)
	end


	def create
		@todo = Todos.new(todo_params)

		if @todo.save
			redirect_to todos_path(@todo), :notice => "Your todo item was created"
		else
			render "new"
		end
	end

	def update
		@todo = Todos.find(params[:id])

		if @todo.update_attribute(:done, true)
			redirect_to root_path, :notice => "Your todo item was marked as done"
		else
			redirect_to root_path, :notice => "Your todo item was !NOT! marked as done"
		end
	end

	def destroy
		@todo = Todos.find(params[:id])
		@todo.destroy
		redirect_to root_path, :notice => "TODO item was deleted"
	end






end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/todo_helper.rb
module TodoHelper
end

app/views/home/index.html.erb
<h1>Welcome to ToDo</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Table</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
	You are currently signed in as <%= current_user.email %>, not you?
	<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
<%else %>
	<%= link_to "SIGN UP", new_user_registration_path %> or <% link_to "SIgn in", new_user_session_path %>
<% end %>

<% flash.each do |name, message| %>
	<%= content_tag :div, message, :id => "flash_#{name}" %>
<% end %>

<%= yield %>

</body>
</html>

app/views/todos/index.html.erb
<h1>TO DO STUFF</h1>

<h2>TODO: </h2>
<% @todos.each do |t| %>

	<p>
		<strong><%= t.name %></strong>
		<small><%= link_to "Mark as DONE", todo_path(t), :method => :put %></small>
		<small><%= link_to "Remove", t, method: :delete, data: { confirm: 'Are you sure?' } %></small>

	</p>
<% end %>

<h2>DONE: </h2>
<% @todone.each do |t| %>

	<p>
		<strong><%= t.name %></strong>
		<small><%= link_to "Remove", t, :confirm => "Shure?", :method => :delete %></small>


	</p>
<% end %>

<p><%= link_to "Add new item to the list", new_todo_path %></p>

app/views/todos/new.html.erb
<h1>Add new item to the table of todo</h1>
<%= form_for @todo, :url => todos_path(@todo) do |f| %>
	<%= f.label :name %> <%= f.text_field :name %>
	<%= f.hidden_field :done, :value => false %>
	<%= f.submit "add to TODO list" %>
 



<% end %>